# Importe a Biblioteca do madagascar 
from rsf.proj import *

Flow('cubo_out','data',
	'''
	cubo m0=5 verb=1
	''')

#Result('cubo_out','graph')

Result('cubo_out',
	'''
	byte |
	grey3 movie=1 color=j yreverse=y xreverse=n
	title='Dados Modelo refletor gaussiano'
	''')

End()
